language: crystal
services:
  - postgresql
before_script:
  - crystal tasks.cr -- db.create
  - crystal tasks.cr -- db.migrate
script:
  - crystal spec
  - crystal tool format src spec --check
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: authentic
  on:
    branch: master
  local_dir: docs
