#! /bin/bash

# Exit if any subcommand fails
set -e
set -o pipefail

docker-compose up -d

COMPOSE="docker-compose exec app"

printf "\nSetting up database\n\n"
$COMPOSE crystal tasks.cr db.setup

printf "\nRunning specs\n\n"
$COMPOSE crystal spec

printf "\nChecking code formatting\n\n"
if ! $COMPOSE crystal tool format --check src spec > /dev/null; then
  printf "\nCode is not formatted.\n"
  printf "\nFormat the code with: docker-compose run --rm app crystal tool format src spec\n\n"
  exit 1
fi

docker-compose down
