name: Authentic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  check_format:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install shards
        run: shards install
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
  specs:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        postgres_version:
          - 16
        crystal_version:
          - 1.10.0
          - latest
        experimental:
          - false
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup PostgreSQL v${{ matrix.postgres_version }}
        uses: ikalnytskyi/action-setup-postgres@v6
        with:
          username: lucky
          password: developer
          port: 5432
          postgres-version: ${{ matrix.postgres_version }}
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal_version}}
      - name: Install shards
        run: shards install --skip-postinstall --skip-executables
      - name: Run tests
        run: crystal spec
        env:
          DATABASE_URL: postgres://lucky:developer@localhost:5432/authentic_test
