name: Authentic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  check_format:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v1
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.4.1
      - name: Install shards
        run: shards install
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 1.4.0
          - latest
        experimental:
          - false
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: lucky
          POSTGRES_PASSWORD: developer
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal_version}}
      - name: Install shards
        run: shards install
      - name: Setup Database
        run: crystal tasks.cr db.setup
        env:
          DATABASE_URL: postgres://lucky:developer@localhost:5432/authentic_test
      - name: Run tests
        run: crystal spec
        env:
          DATABASE_URL: postgres://lucky:developer@localhost:5432/authentic_test
